### ISSUE TITLE
[BUG] Chests retain unique identifier when broken before trade sign

### ISSUE THREAD

**Issue by VanirDev** [SparklingComet/TradeShop#70]
Chests with a trade sign on them are renamed to act as a unique identifier (I presume). When the sign is destroyed, the chest has this identifier removed. 

If the chest is destroyed with the sign still attached, the chest will retain this identifier. If this chest is placed down again and has a sign placed on it to create a new shop, the sign will throw a "no inventory available" error meaning unless the player renames it in an anvil, it can't be used to make another shop.

I've had some players accidentally do this, and obviously not understand why their shop isn't working.

**Comment by paularcoleo** [comment]
Some additional context for how to recreate this bug:

1. Place down a single chest, this will be called Chest 1.
2. Add any TradeShop sign to it.
3. Place down a second chest next to it (this can either be a separate chest, or create a double chest). This will be called Chest 2.
4. Add a second Tradeshop sign to Chest 2. This will create an invalid Tradeshop sign, as the doublechest protection is being extended from Chest 1 to Chest 2, and therefore they are being considered the same inventory block,  and you get the `You may only have 1 shop per inventory block.` error message. (Will come back to this momentarily).
5. Break Chest 1 before breaking the sign on Chest 1 and Chest 1 will become a bugged chest, retaining the ID value on the chest. 
5a. While chests with different IDs do not stack, it is possible to get chests with the same ID by repeating steps 1-5 at the same coordinates.
5b. In some cases, placing a bugged chest back down again and attempting to add a new TradeShop sign to it will cause an error, and then breaking the sign then chest will properly revert the chest, but this is not always the case.

What I mentioned in step 4 has two different issues, which may warrant their own tickets:
**A.** I don't think that the functionality of TradeShops should be that if a new single chest is placed down to a different single chest with an existing tradeshop sign that TS would consider the new chest part of the existing one. Perhaps there needs to be a check when the new chest is being placed whether or not the player is sneaking (which is how you can force the game to put down a single chest, rather than a double chest.) If the player is sneaking, then it wouldn't become part of the existing shop.

**B.** You actually can put more than 1 shop sign on a single double chest. Currently, double chest protection is dependent on the order in which you place the chests and tradeshop sign. If you place chest 1, then make a sign, then chest 2, then as described above, they will be considered the same inventory block. However, if you place both chests to create a double chest, and then add the tradeshop sign, you can add two tradeshop signs to the double chest. This has an upside and a downside. The downside is that if a user sets up their chest this way, but doesnt put down a second sign, the side of the double chest without a sign is vulnerable to being broken. The upside is that this allows you to make an asymmetric BiTrade, by putting two different trades on the same double chest. For example, maybe you want to sell 32 black dye / diamond to players out of your chest, but you want to buy black dye from players at 48 / diamond. You could accomplish this by putting a Tradeshop sign for each of those trades on either half of the double chest.

Overall, it seems that the protection of double chests is a bit inconsistent, and a player may either be making their shops vulnerable or bugging out their chests without being able to understand why or how to fix it.

**Comment by KillerOfPie** [comment]
1) The names on the chest is not a new bug, I have fixed it so idk why its back. 
2) The chests next to each other is a newer feature in MC

I would work on attempting to fix this, however, I believe the better solution will be to just get rid of the named chest system sooner, and change how the system checks chest. As soon as i fix the other bugs in 2.2, I will begin working on this for the 2.3 update.

**Comment by paularcoleo** [comment]
I just learned that this bug is not exclusive to chests. It can also be replicated with Shulker boxes, and presumably other containers as well. Hopefully moving away from naming the items will fix this. However, I think that there is a separate & compounding problem that I will make a new github issue for. 

![shulker](https://user-images.githubusercontent.com/14979976/78617580-a5932700-782c-11ea-8294-db912bc14538.png)

**Comment by KillerOfPie** [comment]
The names are all exactly the same problem and will exist on any item that was used as shop storage. Moving away will completely fix any problems related to this as the names will never be added in the first place.

**Comment by KillerOfPie** [comment]
this should also be fixed in 2.2.2
