### ISSUE TITLE
[FEATURE] Ability to not specify certain attributes on cost/products

### ISSUE THREAD

**Issue by paularcoleo** [SparklingComet/TradeShop#78]
Trying to set up a shop concept where a user could return a specific pickaxe at any durability and receive a fully repaired pickaxe in return. However, currently the only way to specify the name/enchantments for a product or cost is to hold the item in your hand when using `setCost` or `setProduct` commands and leaving the material argument blank. But this also records the specific durability of the item being held (Damage tag). Thus, two otherwise identical pickaxes at Damage 1 (durability 1560/1561) and Damage 2 (durability 1559/1561) are considered different items. By contrast, typing "diamond_pickaxe" with no other information will allow any diamond pickaxe regardless of name, durability, or enchantments to be used as a product or cost. I understand why this is the case, but certainly there is a use case for a middle ground between "anything goes" and strictly exact NBT matching?

Sidenote: this is somewhat related to #75, as it pertains to the exact ordering of items as defined by the NBT attributes. A similar "anything goes" example analogous to the example above can be achieved by typing "shulker_box" as the product or cost.

I tried to specify only the NBT attributes I cared about (name, enchantments) using setcost, but that doesn't seem to be supported, as I only got "Try /tradeshop help" message by doing so.

**Comment by KillerOfPie** [comment]
1. This would be different than #75 as that is conering how we compare items inside the shulker when trading. 

2. Due to how complex NBT tags can be and how they change with each item I don't see us adding the ability to specify specific tags anytime soon. This should be something that is possible to be added on using our Add-On Framework

3. My solution to this will be a couple things:
  A. Make the add and set commands not use exact placement of the variables but rather based on what they are i.e if you were to do `/ts setcost diamond_pickaxe 2` if diamond_pickaxe is an valid material then it will use that as the material, and likewise it will check for a integer variable for the amount.
  B. I will add an additional variable that will start with `dur`... So lets say that you want to receive diamond pickaxes under 200 durability you would add the variable `dur<200`. this would similarly be made to function with `>` and `=` as well as possibly with 2 numbers for between `dur200:300` as well as percentages `dur<20%`. The later 2 may come later than the rest of the system.
  C. I could also add other values in a similar way, however I don't want to create any way for someone to accidentally trade an item(currently naming it is a good way to prevent such things).

Let me know what you think about my solution or if you have any questions about it. Like i said on discord I dont plan on omplementing this until we finsh the version we are currently working on.

**Comment by KillerOfPie** [comment]
@SparklingComet Let me know what you think of the above solution as well

**Comment by SparklingComet** [comment]
> @SparklingComet Let me know what you think of the above solution as well

I think 3.B would be a very good idea for any kind of tool, as I can totally see some scams happening with items which are about to break.
I would suggest we plan it for v2.3.0 as the current release is already packed with many fixes.

**Comment by KillerOfPie** [comment]
The back-end for this had been made in the latest dev release (and is usable through editing the shop storage files, but not in game), my current thoughts are to use the new Inventory GUI API I added to make shops customizable through much easier to understand guis, including item options like this.

**Comment by KillerOfPie** [comment]
@paularcoleo this has been added to #92 as well as the most recent dev release https://github.com/Tradeshop/TradeShop/releases/tag/tradeshop-2.3.0-DEV-2020-11-04T03.00.11
