### ISSUE TITLE
[BUG] signed books not properly usable as products or costs 

### ISSUE THREAD

**Issue by paularcoleo** [SparklingComet/TradeShop#79]
Server I play on is currently running 2.2.0-BETA, When testing how to create a voucher-like system which would allow the use of an item that could only have been created by the shop owner, I looked to signed books as an option. Tradeshop allows the usage of `/ts setcost 1` and `/ts setproduct 1` when holding the specific book, and the specific book shows up properly in the `/ts what` GUI, however it does not properly interact in the store.

If used as a cost,  the shop does not recognize the item in the inventory, and gives an error along the lines of "you do not have 1 written_book".

If used as a product, the shop does not recognize the item in the container as being the product being sold, and if interacted with automatically closes the shop, as it is considered to not have inventory.

**Comment by RobinWhitfield** [comment]
On the latest dev build (tradeshop-2.2.2-BETA-2020-05-13T18.07.43.jar):

It's giving out what seems to be an identical book as a product item, but it's not identical (items don't stack). It's using the presence of a written book to check stock, but not a specific written book.
It's not taking out any stock from the chest when a trade is completed, but it does give the (apparently identical but not identical) item to the player doing the trade.

It's accepting any written_book as a cost item rather than a specific written book, even when a specific book is used to set the cost.

**Comment by KillerOfPie** [comment]
I was finally able to fix this in the newest dev release
